name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: latest
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: make

      - name: create SHA256
        run: shasum -a 256 build/filzasbx.dylib > build/filzasbx.dylib.sha256

      - name: publish release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest
          make_latest: true
          generate_release_notes: true
          files: |
            build/filzasbx.dylib
            build/filzasbx.dylib.sha256
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
